### ISSUE TITLE
Замена данных при добавлении по ссылке

### ISSUE THREAD

**Issue by veopot** [veopot/mwx-json#40]
**manga_link_corrector** для замены ссылки на мангу динамически
 (remanga ,mangadex,newmanga)

Для облегчения добавление манги с данных сайтов ссылкой для пользователей 

Примерный вариант данной функции
```
"link_corrector": [
            {
                "match": "remanga.org/manga/",
                "text": "api.remanga.org/api/titles/"
            }
        ]


```

**Comment by veopot** [comment]
При добавлении манги ссылкой 
надо часть ссылки изменить 

то есть если в ссылке есть
 "match": "remanga.org/manga/",
то надо  в ссылке часть изменить на 
 "text": "api.remanga.org/api/titles/"

**Comment by LomikXP** [comment]
Так, в связи с тем что в [manga_complete].[link_corrector] используется под нужды глав, то при добавлении по ссылке будет использоваться [manga_list_complete].[link_corrector]

**Comment by LomikXP** [comment]
Так же внимание, так как корректоры это массив то каждый корректор добавит одну ссылку после замены и затем ссылка проверяется и связывается с парсером и указывается как источник для манги

**Comment by LomikXP** [comment]
На текущий момент иного использования [manga_list_complete].[link_corrector] не предусмотрено
