### ISSUE TITLE
Требуется доработка referer

### ISSUE THREAD

**Issue by veopot** [veopot/mwx-json#45]
Походу ты referer не доделал

В 3.1.6.2 
Протестировал 
Добавлял и удалял 
"Referer": "https://com-x.life/",
 из парсера 

Всеровно всплывает запрос пройти капчу 

Но я протестировал 
Запрос 
https://com-x.life/uploads/posts/2019-07/1562581966_00_1.jpg

Если передать на обложку 
"Referer": "https://com-x.life/"
Капчу просить не будет

**Comment by LomikXP** [comment]
Сейчас алгоритм такой для добавления header при загрузке обложки:
1. Берутся все заголовки из [mangacomplete].[add_chapter].[headers]
2. Если нет [mangacomplete].[add_chapter].[headers], то берется [mangacomplete].[headers]
