### ISSUE TITLE
Проблема с чтением сканов иза спецсимволов 

### ISSUE THREAD

**Issue by veopot** [veopot/mwx-json#56]
Суть проблемы 

Есть манга

https://v1.slashlib.me/mods

У человека жена жалуется что не качает!
При тесте 
Проверил глава 6,
 при попытке скачать выдает нет свободного места в mangawatcherx

Хотя свободно 20гб

С другими   тайтлами такой проблемы нет

После проверки ссылок на сканы на все сканы присутствуют скобки в адресе скана на сайте пример
MODS_AS_000_[Himawari].png

Подозреваю и за них вся проблема

**Comment by LomikXP** [comment]
Нужен другой пример, а то у меня не открывается этот
