### ISSUE TITLE
Доработка сортировки глав по числам

### ISSUE THREAD

**Issue by LomikXP** [veopot/mwx-json#62]
Переработан порядок с учетом экстра в виде дробных частей
Переработан учет разных нумераций:
теперь дополняется слева
[0т] 100 глава
1 том 10 глава
раньше дополнялось справа
1 том 10 глава
100 глава [0т]

**Comment by idMysteries** [comment]
Не думаю, что это так должно быть. Том 1 всё же должен быть внизу, кажется.
![Screenshot_20240217-204230](https://github.com/veopot/mwx-json/assets/11484976/6bcb8ca9-38bf-4396-ae30-e7405ce9658a)
![Screenshot_20240217-204235](https://github.com/veopot/mwx-json/assets/11484976/744c7dac-4c58-4d49-8d42-8df22c83ac1d)

**Comment by idMysteries** [comment]
![Screenshot_20240217-211128](https://github.com/veopot/mwx-json/assets/11484976/d446ec2c-89e3-4901-8eb2-ef67e5884e6f)

**Comment by veopot** [comment]
Востоновлено 

Вопрос открыт
