### ISSUE TITLE
Баг) игнор скачанных глав 

### ISSUE THREAD

**Issue by veopot** [veopot/mwx-json#65]
Удаляет уже скаченные главы 

![Screenshot_2023-10-22-11-06-18-042](https://github.com/veopot/mwx-json/assets/966464/a2caeb75-06ad-4fd9-9e70-bfc56fea9c66)

![Screenshot_2023-10-23-22-10-52-594](https://github.com/veopot/mwx-json/assets/966464/313f499d-cba8-4dc6-ae49-f52f97856bab)

Дополнение
Игнорит функцию 
"Заблокировать главы от удаления "

**Comment by LomikXP** [comment]
Вероятно дубликат для issue 70
