### ISSUE TITLE
Удаляются главы заблокированные для удаления

### ISSUE THREAD

**Issue by veopot** [veopot/mwx-json#70]
Игнорит функцию
"Заблокировать главы от удаления "

![Screenshot_2023-11-10-12-24-41-975](https://github.com/veopot/mwx-json/assets/966464/90bf13f3-6944-4d30-a626-bd2b1f2fcfe7)

Удаляет полностью список глав

Хотя главы на сайте есть 
И без разницы какой источник манги

**Comment by LomikXP** [comment]
А какое действие совершаешь? Как именно удаляется

**Comment by LomikXP** [comment]
В рамках бага будет исправлено определение статуса что глава скачана
