### ISSUE TITLE
Добавить поддержку 64 битой версии приложения

### ISSUE THREAD

**Issue by veopot** [veopot/mwx-json#73]
Подскажите, планируется ли выпуск 64 битой версии приложения?
 К сожалению, мой смартфон не поддерживает 32 битные приложения от слова совсем

**Comment by LomikXP** [comment]
Приложение включает 64-битные библиотеки, а как именно проявляется "не поддерживает"?

**Comment by veopot** [comment]
> Приложение включает 64-битные библиотеки, а как именно проявляется "не поддерживает"?

Написал человеку который просил, должен тут ответить

**Comment by maj0nez** [comment]
![Screenshot_20231215-220854](https://github.com/veopot/mwx-json/assets/153948519/a9fc1eb4-7ebe-45b5-ad95-c92201c22326)
Прилагаю скриншот с ошибкой
Устройство pixel 7, android 14

**Comment by vitalii-malasherifov** [comment]
Добрый день, 
Столкнулся с аналогичной проблемой на S24U (Snapdragon 8 Gen 3, 64bit only), Tango транслятор не интегрирован (как в 1+ 12, Xiaomi 14 Pro).

Библиотеки 64 бит есть в самом приложении, но в процессе установки выскакивает ошибка о несовместимости.
Если требуется - могу попробовать снять логи, [если подобное решение сработает и подойдет](https://android.stackexchange.com/questions/220625/how-to-get-installation-log-either-from-adb-install-or-manual-install)

**Comment by Last8Exile** [comment]
Только приехал RedMagic 9 на снапе 8 ген 3.
Три приложения старых не встали из-за проблем с 64 кодом. Не проверял есть ли он там или как тут - не совместим. Видать нужно рекомпилить приложение и все нативные библиотеки свежим ndk.

**Comment by veopot** [comment]
Ждем ответа разработчика @LomikXP

**Comment by LomikXP** [comment]
Дубликат #74
