### ISSUE TITLE
Нет поддержки x64 процессоров

### ISSUE THREAD

**Issue by Mozgurt** [veopot/mwx-json#85]
**Опишите ошибку**
Нет возможности установки на телефон с процессором dimesity 8300
**Заголовок **

** Версия приложения**
  - Версия [например.  3.1.6.4 ]

 **Смартфон (пожалуйста, заполните следующую информацию):**
  - Устройство: poco x6 pro 5G
  - ОС: Xiaomi hyperos 1.0.8.0 android 14
  - mediatek dimensity 8300 ultra

**Для воспроизведения**
 Шаги для воспроизведения поведения:
 1. Перейдите в раздел «...»
 2. Нажмите «....»
 3. Прокрутите вниз до «....»
 4. См. ошибку
 (шаги которые приводят к этой ошибке, какой результат ожидаете и т.д.) 

*"Если проблема с мангой с источниками**
Предоставить на какой именно главе.

 **Скриншоты**
 Если применимо, добавьте снимки экрана, которые помогут объяснить вашу проблему.
 или видео об ошибке

 **Дополнительный контекст**
 Добавьте сюда любой другой контекст проблемы.

**Comment by veopot** [comment]
Нет ответа закрываем,
