### ISSUE TITLE
Возможность добавить мангу в исключения для обновления

### ISSUE THREAD

**Issue by KaPTOFFaH** [veopot/mwx-json#93]
При длительном использовании приложения, скапливается много уже прочитанной манги. Удалять ее из библиотеки желания нет, не хочется потом вспоминать что читал, а что - нет. Но каждый раз, когда жмешь кнопку поиска обновлений, приложения ищет обновления для всей твоей библиотеки, из-за чего поиск обновлений может затянуться.

Предлагаю добавить исключения для обновлений, чтобы читатель мог выбрать, что исключить.  Или сделать отдельную категорию "прочитано", при добавлении в которую манги, она перестанет искать обновления

**Comment by veopot** [comment]
Добрый день есть такая функция 

Зайдите в настройки в раздел скачивание

Там в низу включите галочку проверять только мангу со
Статусом продолжается  

И после этого при обновлении манга у которой статус завершено будет проигнорирован

**Comment by veopot** [comment]
![Uploading Screenshot_2024-07-23-13-49-22-575.jpeg…]()

**Comment by veopot** [comment]
![Uploading Screenshot_2024-07-23-13-49-22-575.jpeg…]()
