### ISSUE TITLE
Не работает авторизация для сетевого репозитория

### ISSUE THREAD

**Issue by CaptainCarp** [veopot/mwx-json#96]
Не срабатывает функция авторизации в сетевых репозиториях. При нажатии в течение 3 секунд на ссылку репозитория действительно появляется контекстное меню с опцией "Войти", но выбор этой опции не имеет совершенно никакого эффекта, не происходит перехода к собственно вводу логина и пароля для входа. Контекстное меню просто закрывается и на этом всё завершается.

** Версия приложения**
  - Версия 3.1.6.8

 **Смартфон (пожалуйста, заполните следующую информацию):**
  - Устройство: Xiaomi Pad 6
  - ОС: Android 14

**Comment by veopot** [comment]
Подробнее Яндекс диск или гугл диск

Или на какой та сайт ?

**Comment by CaptainCarp** [comment]
![1725799589836](https://github.com/user-attachments/assets/aba4b987-4ec4-466d-add3-573a1665178f)

**Comment by veopot** [comment]
А если серым горит значит для данного сайта не требуется данное действие 

Да и данный тип авторизации устарел

Если вы пытаетесь на ком-х но с ним проблема с обходом зашиты cloudflare а сайт отказывается дать для приложения доступ по юзер агенту

**Comment by CaptainCarp** [comment]
Совершенно верно, пытаюсь открыть мангу/комикс через ком-х, но ничего не получается из-за ошибки обхода cloudflare, сайт требует дополнительного действия, происходит переход на страницу комикса и в общем-то всё) То есть это конкретно с данным сайтом такая проблема потому что они не хотят сотрудничать?

**Comment by veopot** [comment]
Ага вначале com-x говорили использовать user-agent 
Посвежее а топом с этим cloudflare проблемы,
Просил добавить тогда для программы  user-agent
 Типо mangawatcher но они отказались 

У некоторых сайты идут на встречу у которых cloudflare и делают  user-agent для приложения

**Comment by CaptainCarp** [comment]
Понял, в таком случае вопрос закрыт. Жаль, у них хорошая библиотека.

**Comment by veopot** [comment]
Можете попробовать написать им сами может если будет больше запросов сделают 
Пример нам такое надо "userAgent": "mangawatcherx"

**Comment by CaptainCarp** [comment]
Попробовал пообщаться, но Com-x, к сожалению, явно не желают что-либо менять, им и так хорошо.
