### ISSUE TITLE
Comicastle.org больше не работает

### ISSUE THREAD

**Issue by andorus911** [veopot/mwx-json#98]
Окно парсера Comicastle, жму на любой комикс:
Загрузка...
Unable to resolve host "comicastle.org": No address associated with hostname
Не удалось добавить мангу!

Comicastle.org больше нет. Но я находил https://www.comic.nizamkomputer.com/, судя по всему, они называют себя Comicastle.

  - Версия 3.1.6.8 

  - Устройство: Андроид 
  - ОС: 13

**Comment by veopot** [comment]
Принято, на выходные постараюсь посмотреть

**Comment by veopot** [comment]
ee35c972cab18d43c908fa204e510fa33b9c8d3b

Востоновил
